### PR TITLE
Improve spam protection

### PR DESCRIPTION
**Pull request by the-sageman**
A.K.A. use a readily available library to improve CAPTCHA quality
It also clears all previously generated captchas on startup in case the administrator has deleted some in the `public` directory.
ImageMagick can remain as a requirement for the future for thumbnailing.
I can also add the option to configure the parameters for CAPTCHA generation, but I don't think this is needed.

Example 1
Example 2

### CODE REVIEW

**Comment by FChannel0** [comment]
While this would make things less spam-able there is hate for captcha because of how they can be difficult to read. These examples demonstrate that. 
I wonder if there is a fine line to walk where the captcha is more difficult to abuse and has user friendliness to not drive the user base insane.  

These are the v2 captcha  I was working on that I didnt release. There could be some more artifacts overlayed to obscure more. 

https://ibb.co/4f7Xsvv
https://ibb.co/j3K73tB

Security is important, but user friendliness is too. I dont want to log user information such as ips at the moment to remove captchas so they are a necessary evil for the moment. I would like to discuss more about the captchas and what the user base would tolerate.

I do agree the current captcha are not secure if someone really wants to try and abuse the system and a new one needs to be in its place.

**Comment by the-sageman** [comment]
> While this would make things less spam-able there is hate for captcha because of how they can be difficult to read. These examples demonstrate that.
> I wonder if there is a fine line to walk where the captcha is more difficult to abuse and has user friendliness to not drive the user base insane.

> Security is important, but user friendliness is too. I dont want to log user information such as ips at the moment to remove captchas so they are a necessary evil for the moment. I would like to discuss more about the captchas and what the user base would tolerate.

Perhaps something similar can be implemented to multichan's solution, like a captcha that is valid for a certain amount of time so that you don't have to retype it every time. Obviously readibility is problematic, I already tweaked on the fonts a bit, but more user feedback is needed and you can't get that without testing it on the big scale.

**Comment by knotteye** [comment]
> I dont want to log user information such as ips at the moment to remove captchas so they are a necessary evil for the moment.
This may become necessary in the future anyway, fchannel will need a system for banning users at some point. I haven't seen any malicious actors on the network yet, but it's only a matter of time.

**Comment by FChannel0** [comment]
> Perhaps something similar can be implemented to multichan's solution

multichan stores ips for their captchas, i want to try and store as little user data as possible. I guess cookies could be implemented to ease the captcha annoyances. 

And yeah there has to be feedback. Ill make a captcha related post today and get user feedback. Users will be interacting with it 100% of the time so need their input.

@knotteye 
>but it's only a matter of time.
Yes, and I am trying to think of the best way to approach it with respecting user data.

**Comment by the-sageman** [comment]
> I guess cookies could be implemented to ease the captcha annoyances.

The session cookie can already be used for that purpose

**Comment by majestrate** [comment]
on the topic of bans, nntpchan implements distributed IP bans by putting a ciphertext block into every post which has a matching pad that when xor'd together reveals the poster's IP address, this is a deniable scheme so the origin has the ability to lie but also no way to prove it really is the real IP. when a server wants to tell other servers to IP ban a user on their server they release the pad and ciphertext to the network revealing the poster's ip address, because all moderation messages are cryptographically signed this cannot be spoofed. this scheme was the best i could come up with that has a balance between "privacy" and being ale to actually ban ip addresses web of trust style.

**Comment by majestrate** [comment]
as for captchas, it's not possible to enforce them network wide, i don't think there is any way to.

**Comment by FChannel0** [comment]
> as for captchas, it's not possible to enforce them network wide, i don't think there is any way to. it's still a great idea to have them though.

yeah they are not the best solution, but its a solution that prevents some spam. as far as other instances disabling spam protection that is an instance issue and if not taken care of others might remove themselves from those feeds.

i do like the idea of the posts embedded with the ip cipher and is most likely the way to go. its only a matter of time before someone poo poos everywhere. i thought i could get away without ip data, but it seems necessary. web is dirty and is blasting your ip everywhere anyways. and instances will need the ability to ban/suspend users eventually.

**Comment by the-sageman** [comment]
@FChannel0 not a whole lot of feedback has arrived so far in your thread, only 2 replies.
I say that we should organize an A/B test, one captcha is mine, while the other is your new one. The only data this test would collect is the amount of captchas succeeded and the amount of captchas that failed by captcha type. This test would be pushed to the development branch for a few weeks and deployed to fchan.xyz and then reverted later.
I know that you are not a fan of data collection, but unlike IP addresses, the data collected by this method cannot identify users. It only shows the general opinion about the captchas and it will help to close this PR once and for all.

**Comment by 0jsc** [comment]
You'd probably do good to have different CAPTCHAs for different instances. That provides a natural A/B test; if the CAPTCHA is too easy, the instance will get spammed to shit, if the CAPTCHA is too hard, nobody will post there.

In the long run, you'll probably need some kind of auth, at least for onions - CAPTCHA simply isn't powerful enough. Even if the system is perfect, spammers can hire 1,000,000 Indians to solve captchas for $1/hour.

**Pull request closed without merging**
